---
details:
  welcome_message: "Sample message, there once 5 was a man who sailed to northern egypt only to find Sample message, there once 5 was a man who sailed to northern egypt only to find Sample message, there once 5 was a man who sailed to northern egypt only to find"

formats:
  current_date_time_format: "%b %d, %Y" # "%m/%d/%y" using format specifiers
  # uptime_format:

displays:
  should_display_image: true
  should_display_blocks: true
  should_display_text: true

alignments:
  space_before: 2
  space_after: 2
  lines_before: 2
  lines_after: 2
  hr_node_repeat: 18
  word_wrap: 30
  color_block_padding: 4

chars:
  hr_divider_node: 0x2219
  # Bullet chars
  default_bullet: 0x2219
  sys_distro_bullet: 0xfb32
  sys_shell_bullet: 0xf489
  current_date_time_bullet: 0xf073
  # sys_architecture_bullet: 0xf109
  # cpu_bullet: 0xe266
  # ram_bullet: 0xe266
  # uptime_bullet: 0xf017

colors:
  default_text_color: White
  username_color: LightYellow
  device_name_color: LightGreen
  welcome_message_color: LightGreen
  hr_color: LightBlue
  # Bullet colors
  default_bullet_color: Red
  sys_distro_bullet_color: LightRed
  sys_shell_bullet_color: LightYellow
  current_date_time_bullet_color: LightBlue

overrides:
  username_override: Jagnano
  device_name_override: Lenix
  sys_distro_override: LOSE
  sys_shell_override: DDRELL
